# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

%global crate cosmic-player

Name:           cosmic-player
Version:        0.1.0
Release:        %autorelease
Summary:        # FIXME

SourceLicense:  None
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown
# FIXME: No license information in crate metadata.

URL:            # FIXME

# To create these sources:
# * git clone the repository
# * cargo vendor > .vendor/config.toml
# * tar -pcJf $name-$commit-vendor.tar.xz and move
#     the tar out of the repo directory
# * tar -pcJf $name-$commit.tar.xz
Source:         # FIXME
Source:         cosmic-player-0.1.0-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/cosmic-player

%changelog
%autochangelog
