# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

%global crate cosmic-launcher

%global ver ###
%global commit ###
%global date ###

Name:           cosmic-launcher
Version:        %{ver}~%{date}
Release:        %autorelease
Summary:        Pop launcher frontend for the COSMIC Desktop Environment.

SourceLicense:  GPL-3.0
License:        GPL-3.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/pop-os/cosmic-launcher
Source:         cosmic-launcher-%{ver}.tar.xz
Source:         cosmic-launcher-%{ver}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  wayland-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  just

Requires:       pop-launcher

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{ver} -p1 -a1
%cargo_prep -N
cat .vendor/config.toml >> .cargo/config

%build
export RUSTFLAGS="$RUSTFLAGS --cfg tokio_unstable"
cargo build --release --frozen --offline
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
just rootdir=%{buildroot} prefix=%{_prefix} install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.md
%license LICENSE.dependencies
# %%license cargo-vendor.txt
%doc README.md
%{_bindir}/cosmic-launcher
%{_datadir}/applications/com.system76.CosmicLauncher.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicLauncher.svg
%{_metainfodir}/com.system76.CosmicLauncher.metainfo.xml

%changelog
%autochangelog
