# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

%global crate system76-power

Name:           system76-power
Version:        1.1.25
Release:        %autorelease
Summary:        # FIXME

SourceLicense:  None
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown
# FIXME: No license information in crate metadata.

URL:            # FIXME
Source:         # FIXME
Source:         system76-power-1.1.25-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}
sed 's/\(.*\) (.*#\(.*\))/\1^git\2/' -i cargo-vendor.txt

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%doc TESTING.md
%{_bindir}/system76-power

%changelog
%autochangelog
