# Generated by rust2rpm 26
%bcond_without check

%global ver ###
%global commit ###
%global date ###

Name:           pop-launcher
Version:        %{ver}~%{date}
Release:        %autorelease
Summary:        Modular IPC-based desktop launcher service.

SourceLicense:  GPL-3.0-only AND MPL-2.0
License:        GPL-3.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/pop-os/launcher
Source:         pop-launcher-%{ver}.tar.xz
Source:         pop-launcher-%{ver}-vendor.tar.xz

Patch:          symlink.patch

BuildRequires:  cargo-rpm-macros >= 25
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  mesa-libEGL-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  just

Requires:       libqalculate
Requires:       rust-fd-find

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n pop-launcher-%{ver} -p1 -a1
%cargo_prep -N
cat .vendor/config.toml >> .cargo/config

%build
# %%cargo_build
cargo build -p pop-launcher-bin --release --offline --frozen
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
just rootdir=%{buildroot} install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license plugins/COPYING
%license LICENSE.dependencies
# %% license cargo-vendor.txt
%doc README.md
%{_bindir}/pop-launcher-bin
%{_prefix}/lib/pop-launcher/*

%changelog
%autochangelog
