# Generated by rust2rpm 26
%bcond_without check

Name:           cosmic-bg
Version:        0.1.0
Release:        %autorelease
Summary:        # FIXME

SourceLicense:  
# FIXME: paste output of %%cargo_license_summary here
License:        GPL-3.0
# LICENSE.dependencies contains a full license breakdown

URL:            # FIXME
Source:         # FIXME
Source:         cosmic-bg-0.1.0-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 25

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic-bg-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.md
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/cosmic-bg

%changelog
%autochangelog
