# Generated by rust2rpm 26
%bcond_without check

Name:           cosmic-applets
Version:        0.1.0
Release:        %autorelease
Summary:        # FIXME

SourceLicense:  GPL-3.0-or-later
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

URL:            # FIXME
Source:         # FIXME
Source:         cosmic-applets-0.1.0-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 25

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic-applets-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%{_bindir}/cosmic-app-list
%{_bindir}/cosmic-applet-audio
%{_bindir}/cosmic-applet-battery
%{_bindir}/cosmic-applet-bluetooth
%{_bindir}/cosmic-applet-minimize
%{_bindir}/cosmic-applet-network
%{_bindir}/cosmic-applet-notifications
%{_bindir}/cosmic-applet-power
%{_bindir}/cosmic-applet-status-area
%{_bindir}/cosmic-applet-tiling
%{_bindir}/cosmic-applet-time
%{_bindir}/cosmic-applet-workspaces
%{_bindir}/cosmic-applets
%{_bindir}/cosmic-panel-button

%changelog
%autochangelog
