# Generated by rust2rpm 26
%bcond_without check

%global ver ###
%global commit ###
%global date ###

Name:           cosmic-panel
Version:        %{ver}~%{date}
Release:        %autorelease
Summary:        Panel for the COSMIC Desktop Environment.

SourceLicense:  GPL-3.0
License:        GPL-3.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/pop-os/cosmic-panel
Source:         cosmic-panel-%{ver}.tar.xz
Source:         cosmic-panel-%{ver}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 25
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  wayland-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  just

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic-panel-%{ver} -p1 -a1
%cargo_prep -N
cat .vendor/config.toml >> .cargo/config

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
just rootdir=%{buildroot} prefix=%{_prefix} install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.md
%license LICENSE.dependencies
# %%license cargo-vendor.txt
%doc README.md
%{_bindir}/cosmic-panel
%{_datadir}/cosmic/com.system76.CosmicPanel.Dock/*
%{_datadir}/cosmic/com.system76.CosmicPanel.Panel/*
%{_datadir}/cosmic/com.system76.CosmicPanel/*

%changelog
%autochangelog
