# Generated by rust2rpm 26
%bcond_without check

%global ver ###
%global commit ###
%global date ###

Name:           cosmic-store
Version:        %{ver}~%{date}
Release:        %autorelease
Summary:        App store for the COSMIC Desktop Environment.

SourceLicense:  GPL-3.0
License:        GPL-3.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/pop-os/cosmic-store
Source:         cosmic-store-%{ver}.tar.xz
Source:         cosmic-store-%{ver}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 25
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  flatpak-devel
BuildRequires:  libappstream-glib
BuildRequires:  just

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic-store-%{ver} -p1 -a1
%cargo_prep -N
cat .vendor/config.toml >> .cargo/config

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
just rootdir=%{buildroot} prefix=%{_prefix} install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
# %%license cargo-vendor.txt
%doc README.md
%{_bindir}/cosmic-store
%{_datadir}/applications/com.system76.CosmicStore.desktop
%{_metainfodir}/com.system76.CosmicStore.metainfo.xml
%{_datadir}/icons/hicolor/128x128/apps/com.system76.CosmicStore.svg
%{_datadir}/icons/hicolor/16x16/apps/com.system76.CosmicStore.svg
%{_datadir}/icons/hicolor/24x24/apps/com.system76.CosmicStore.svg
%{_datadir}/icons/hicolor/256x256/apps/com.system76.CosmicStore.svg
%{_datadir}/icons/hicolor/32x32/apps/com.system76.CosmicStore.svg
%{_datadir}/icons/hicolor/48x48/apps/com.system76.CosmicStore.svg
%{_datadir}/icons/hicolor/64x64/apps/com.system76.CosmicStore.svg

%changelog
%autochangelog
