# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

%global crate cosmic-files

%global ver ###
%global commit ###
%global date ###

Name:           cosmic-files
Version:        %{ver}~%{date}
Release:        %autorelease
Summary:        Libcosmic file manager.

SourceLicense:  GPL-3.0-only
License:        GPL-3.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/pop-os/cosmic-files
Source:         cosmic-files-%{ver}.tar.xz
Source:         cosmic-files-%{ver}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  just

BuildRequires:  git-core

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{ver} -p1 -a1
%cargo_prep -N
cat .vendor/config.toml >> .cargo/config

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
just rootdir=%{buildroot} prefix=%{_prefix} install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
# %%license cargo-vendor.txt
%doc README.md
%{_bindir}/cosmic-files
%{_datadir}/applications/com.system76.CosmicFiles.desktop
%{_metainfodir}/com.system76.CosmicFiles.metainfo.xml
%{_datadir}/icons/hicolor/128x128/apps/com.system76.CosmicFiles.svg
%{_datadir}/icons/hicolor/16x16/apps/com.system76.CosmicFiles.svg
%{_datadir}/icons/hicolor/24x24/apps/com.system76.CosmicFiles.svg
%{_datadir}/icons/hicolor/256x256/apps/com.system76.CosmicFiles.svg
%{_datadir}/icons/hicolor/32x32/apps/com.system76.CosmicFiles.svg
%{_datadir}/icons/hicolor/48x48/apps/com.system76.CosmicFiles.svg
%{_datadir}/icons/hicolor/64x64/apps/com.system76.CosmicFiles.svg

%changelog
%autochangelog
