# Generated by rust2rpm 26
# %%bcond_without check
%bcond_with check

%global ver ###
%global commit ###
%global date ###

Name:           cosmic-bg
Version:        %{ver}~%{date}
Release:        %autorelease
Summary:        Background manager for the COSMIC Desktop Environment.

SourceLicense:  MPL-2.0
License:        GPL-3.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/pop-os/cosmic-bg
Source:         cosmic-bg-%{ver}.tar.xz
Source:         cosmic-bg-%{ver}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 25
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  wayland-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  just

Requires:       cosmic-session

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic-bg-%{ver} -p1 -a1
%cargo_prep -N

%build
cat .cargo/config
echo "\n"
cat .vendor/config.toml >> .cargo/config
cat .cargo/config
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
just rootdir=%{buildroot} prefix=%{_prefix} install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.md
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/cosmic-bg
%{_datadir}/applications/com.system76.CosmicBackground.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicBackground.svg
%{_datadir}/icons/hicolor/symbolic/apps/com.system76.CosmicBackground-symbolic.svg
%{_datadir}/cosmic/com.system76.CosmicBackground/*
%{_metainfodir}/com.system76.CosmicBackground.metainfo.xml

%changelog
%autochangelog
