# Generated by rust2rpm 26
%bcond_without check

%global ver ###
%global commit ###
%global date ###

Name:           cosmic-comp
Version:        %{ver}~%{date}
Release:        %autorelease
Summary:        Compositor for the COSMIC Desktop Environment. Can also be used as a standalone compositor.

SourceLicense:  GPL-3.0-only
License:        GPL-3.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/pop-os/cosmic-comp
Source:         cosmic-comp-%{ver}.tar.xz
Source:         cosmic-comp-%{ver}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 25
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  wayland-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  libglvnd-devel
BuildRequires:  libseat-devel
BuildRequires:  libinput-devel
BuildRequires:  mesa-libgbm-devel
BuildRequires:  make

Requires:       libseat

Recommends: cosmic-session

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic-comp-%{ver} -p1 -a1
%cargo_prep -N
cat .vendor/config.toml >> .cargo/config

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
make install DESTDIR=%{buildroot} prefix=%{_prefix}
install -Dm0644 config.ron %{buildroot}/%{_sysconfdir}/cosmic-comp/config.ron

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
# %%license cargo-vendor.txt
%{_bindir}/cosmic-comp
%{_sysconfdir}/cosmic-comp/config.ron

%changelog
%autochangelog
