# FIXME: Debug artifacts get in the way
%define debug_package %{nil}
# Generated by rust2rpm 26
%bcond_without check

%global ver ###
%global commit ###
%global date ###

Name:           cosmic-settings
Version:        %{ver}~%{date}
Release:        %autorelease
Summary:        Settings app for the COSMIC Desktop Environment.

SourceLicense:  GPL-3.0 AND GPL-3.0-only
License:        GPL-3.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/pop-os/cosmic-settings
Source:         cosmic-settings-%{ver}.tar.xz
Source:         cosmic-settings-%{ver}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 25
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  libinput-devel
BuildRequires:  wayland-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  systemd-devel
BuildRequires:  just

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic-settings-%{ver} -p1 -a1
%cargo_prep -N
cat .vendor/config.toml >> .cargo/config

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
just rootdir=%{buildroot} install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.md
%license LICENSE.dependencies
# %%license cargo-vendor.txt
%doc README.md
%{_bindir}/cosmic-settings
%{_datadir}/applications/com.system76.CosmicSettings.desktop
%{_metainfodir}/com.system76.CosmicSettings.metainfo.xml
%{_datadir}/cosmic/com.system76.CosmicTheme.Dark.Builder/v1/*
%{_datadir}/cosmic/com.system76.CosmicTheme.Dark/v1/*
%{_datadir}/cosmic/com.system76.CosmicTheme.Light.Builder/v1/*
%{_datadir}/cosmic/com.system76.CosmicTheme.Light/v1/*
%{_datadir}/cosmic/com.system76.CosmicTheme.Mode/v1/*
%{_datadir}/icons/hicolor/scalable/status/illustration-appearance-dark-style-round.svg
%{_datadir}/icons/hicolor/scalable/status/illustration-appearance-dark-style-slightly-round.svg
%{_datadir}/icons/hicolor/scalable/status/illustration-appearance-dark-style-square.svg
%{_datadir}/icons/hicolor/scalable/status/illustration-appearance-light-style-round.svg
%{_datadir}/icons/hicolor/scalable/status/illustration-appearance-light-style-slightly-round.svg
%{_datadir}/icons/hicolor/scalable/status/illustration-appearance-light-style-square.svg
%{_datadir}/icons/hicolor/scalable/status/illustration-appearance-mode-dark.svg
%{_datadir}/icons/hicolor/scalable/status/illustration-appearance-mode-light.svg
%{_datadir}/icons/hicolor/128x128/apps/com.system76.CosmicSettings.svg
%{_datadir}/icons/hicolor/16x16/apps/com.system76.CosmicSettings.svg
%{_datadir}/icons/hicolor/24x24/apps/com.system76.CosmicSettings.svg
%{_datadir}/icons/hicolor/256x256/apps/com.system76.CosmicSettings.svg
%{_datadir}/icons/hicolor/32x32/apps/com.system76.CosmicSettings.svg
%{_datadir}/icons/hicolor/48x48/apps/com.system76.CosmicSettings.svg
%{_datadir}/icons/hicolor/64x64/apps/com.system76.CosmicSettings.svg
%{_datadir}/applications/com.system76.CosmicSettings.About.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Appearance.desktop
%{_datadir}/applications/com.system76.CosmicSettings.DateTime.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Desktop.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Displays.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Firmware.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Keyboard.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Mouse.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Notifications.desktop
%{_datadir}/applications/com.system76.CosmicSettings.RegionLanguage.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Sound.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Touchpad.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Users.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Wallpaper.desktop
%{_datadir}/applications/com.system76.CosmicSettings.Workspaces.desktop

%changelog
%autochangelog
